baseurl = "https://5f1715e2bf7e2de9f6bc3e31--vigorous-bassi-54f5f3.netlify.app/"
languageCode = "en"
title = "Peter Klipfel"
theme = "hugo-theme-cactus-plus"

# Set the value to true if your site include CJK (Chinese, Japanese, and Korean languages) characters
hasCJKLanguage = false

[params]
	author = "Peter Klipfel"
	description = "My minimalistic portal to the world"
	bio = "biotech<br>music<br>software<br>musings"

	enableRSS = true
	enableToc = true

	enableSummary = true
	# Set the value to true if use description in post front matter replace content summary
	useDescriptionReplaceSummary = false


	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = ""
	about = ""
	archive = ""
	subscribe = ""

	olderPosts = ""
	newerPosts = ""
	copyright = ""

	# show latest posts in single page
	showLatestPosts = false
	readMore = ""

	# Share
	enableShare = false
	tweet = ""
	share = ""

	# 404 page
	title404 = ""
	subtitle404 = ""

  enableDisqus = false
  disqusShortname = "peterklipfel"

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "font-awesome"
  # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
  socialIconStyle = ""


# Add additional social link entries underneath
[social]
	github-square = "https://www.github.com/peterklipfel"

